app:
    resource: "@AppBundle/Controller/"
    type:     annotation
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /create
logout:
    path: /logout
